name: workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Copiar arquivos do repositório
        uses: actions/checkou@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Executar testes
        run: poetry run task test